### ISSUE TITLE
英文OCR效果比较差，有英文的OCR模型吗

### ISSUE THREAD

**Issue by aheluc** [opendatalab/PDF-Extract-Kit#210]
这边主要是抽取arxiv论文，英文有的时候空格和字母都不对

这是论文原文
![Image](https://github.com/user-attachments/assets/439978aa-f6db-4f3a-b11d-1af9207b2629)

抽取出来的markdown：
`
 When obtainingMolecularEmbeddings,wefound thatsomeherbslackedmolec- ular composition in publicly available datasets.To address this issue,we adopt theidea proposed in KDHR|20],using 27-dimensional one-hot encodedprop- erty representations to denote molecular features.Based on the mapping rela- tionshipbetween theproperties andmolecular components ofherbs innetwork pharmacology,aVariationalAutoencoder(VAE)[8]istrainedusingpaireddata of existing 27-dimensional one-hotproperty representations andmolecular rep- resentations.TheVAEcanbedenotedas:  
$$
\mathcal{L}_{V A E}=\mathbb{E}_{q_{\phi}(z|x)}[\log p_{\theta}(x|z)]-D_{\mathrm{KL}}(q_{\phi}(z|x)||p(z)),
$$ 

 where r represents the input 27-dimensional one-hot property representation, $z$ represents the latent variable that captures the underlying molecular structure, theencoder $q_{\phi}(z|x)$ maps $x$ to a distribution over the latent space,and the de- coder $p_{\theta}(x|z)$ reconstructsthemolecularrepresentationfromthelatentvariable $z$ . The loss function $\mathcal{L}_{V A E}$ consists of the reconstruction term $\mathbb{E}_{q_{\phi}(z\vert x)}\lfloor\log p_{\theta}(x\vert z)\rfloor$ 
`

**Comment by myhloli** [comment]
抽arxiv论文不需要开ocr，用pdf内嵌的文本效果最好。

**Comment by aheluc** [comment]
谢谢，我想问一下这个配置文件要怎么改关闭ocr呢

```
inputs: papers
outputs: outputs/pdf2markdown
visualize: True
merge2markdown: True
tasks:
    layout_detection:
        model: layout_detection_yolo
        model_config:
            img_size: 1024
            conf_thres: 0.25
            iou_thres: 0.45
            model_path: models/Layout/YOLO/doclayout_yolo_ft.pt
    formula_detection:
        model: formula_detection_yolo
        model_config:
            img_size: 1280
            conf_thres: 0.25
            iou_thres: 0.45
            batch_size: 1
            model_path: models/MFD/YOLO/yolo_v8_ft.pt
    formula_recognition:
        model: formula_recognition_unimernet
        model_config:
            batch_size: 128
            cfg_path: pdf_extract_kit/configs/unimernet.yaml
            model_path: models/MFR/unimernet_small
    ocr:
        model: ocr_ppocr
        model_config:
            lang: en
            show_log: True
            det_model_dir: models/OCR/PaddleOCR/det/en_PP-OCRv4_det
            rec_model_dir: models/OCR/PaddleOCR/rec/en_PP-OCRv4_rec
            det_db_box_thresh: 0.3
```
